sonar.host.url=http://localhost:9000
sonar.projectKey=jeuMines
sonar.projectName=jeuMines
sonar.projectVersion=1.0
sonar.sources=JeuMines/src
sonar.java.binaries=JeuMines/bin
sonar.sourceEncoding=UTF-8
sonar.token=sqp_49d3763c604dfe772f0d9f4f882b6287b407e355
sonar.scm.provider=git
