sonar.host.url=http://localhost:9000
sonar.token=sqp_49d3763c604dfe772f0d9f4f882b6287b407e355

sonar.projectKey=jeuMines
sonar.projectName=jeuMines
sonar.projectVersion=1.0

sonar.sources=JeuMines/src
sonar.tests=JeuMines/test
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.java.binaries=out/production/JeuMines-20251011T192442Z-1-001
sonar.java.test.binaries=out/test/JeuMines-20251011T192442Z-1-001

sonar.coverage.jacoco.xmlReportPaths=jacoco.xml
